services:
   - docker

env:
   - CONTAINER_NAME: 'flask'

before_install:
   - docker build -t mashimine/circle .
   - docker-compose up -d
   - docker ps -a

script:
        - docker exec -it flask python test/web.py http://0.0.0.0:5000


      

