services:
   - docker

env:
   - CONTAINER_NAME: 'flask'
   - REPO: "mashimine/circle:v1"

before_install:
   - docker build -t mashimine/circle .
   - docker-compose up -d
   - docker ps -a

script:
        - docker exec -it flask python test/web.py http://0.0.0.0:5000

after_sucess:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $REPO


      

