language: python
python: "2.7"

services:
   - docker

env:
   - CONTAINER_NAME="flask"

install:
   - docker build -t mashimine/circle:v1 .
   - docker-compose up -d
   - docker ps -a

script:
   - docker exec -it flask python test/web.py http://0.0.0.0:5000


after_sucess:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - docker push mashimine/circle:v1

deploy:
#        we should add kubernetes deployment with ansible


      

