services:
   - docker

env:
   - CONTAINER_NAME: 'flask'
   - CONTAINER_IP: `docker exec ${CONTAINER_NAME}  ip a | grep 'eth0' | grep 'inet' | awk '{print $2}' | awk -F '/' '{print $1}'`

before_install:
   - docker build -t mashimine/circle .
   - docker-compose up -d
   - docker ps -a

script:
   - if [ `curl ${CONTAINER_IP}:5000` == "Hello world" ]; then
     echo 'TEST OK'; else
     echo 'TEST FAILED';
     fi


      

